site_name: DbUp
theme: readthedocs
repo_url: https://github.com/DbUp/DbUp

nav:
- Home: index.md
- 'Breaking Changes': breaking-changes.md
- History: history.md
- 'Philosophy Behind DbUp': philosophy-behind-dbup.md
- Usage: usage.md
- 'Supported Databases': supported-databases.md
- FAQ: faq.md
- Contributing: contributing.md
- 'DBOps Powershell Module': dbops.md

- 'More Info':
  - 'Schema Downgrading': more-info/schema-downgrading.md
  - 'Script Providers': more-info/script-providers.md
  - 'Script Types': more-info/script-types.md
  - Transactions: more-info/transactions.md
  - Pre-Processors: more-info/preprocessors.md
  - Logging: more-info/logging.md
  - Journaling: more-info/journaling.md
  - 'Variable Substitution': more-info/variable-substitution.md
  - 'Convention Check': more-info/convention-check.md
  - 'Html Report': more-info/html-report.md
  - 'Run Group Order': more-info/run-group-order.md
